[build]
  command = "npm run build"
  publish = "dist"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicitly ignore the assets folder from SPA fallback
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
