export { About } from './About';
export { Skills } from './Skills';
export { Experience } from './Experience';
export { Education } from './Education';
export { Contact } from './Contact';
export { Hero } from './Hero';
export { Expertise } from './Expertise';
export { ScrollingBanner } from './ScrollingBanner';
export { Achievements } from './Achievements';